spring:
  datasource:
    url: jdbc:postgresql://db:5432/email_signup
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8080

# AWS SES Configuration
aws:
  region: us-east-1
  access-key-id: ${AWS_ACCESS_KEY_ID:your-access-key}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:your-secret-key}
  ses:
    from-email: ${AWS_SES_FROM_EMAIL:danielthai6570@gmail.com}
