spring:
  datasource:
    url: jdbc:postgresql://db:5432/email_signup
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8080

# AWS SES Configuration
aws:
  region: us-east-1
  access-key-id: ${AWS_ACCESS_KEY_ID:your-access-key}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:your-secret-key}
  ses:
    from-email: ${AWS_SES_FROM_EMAIL:danielthai6570@gmail.com}

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
    version: openapi_3_0
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntax-highlight:
      activated: true
    doc-expansion: none
    default-models-expand-depth: -1
    disable-swagger-default-url: true
    display-request-duration: true
    persist-authorization: true
    layout: StandaloneLayout
    deepLinking: true
    displayOperationId: false
    defaultModelRendering: model
    supportedSubmitMethods:
      - get
      - post
      - put
      - delete
  packages-to-scan: com.email.signup.controller
  paths-to-match: /api/**
  show-actuator: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
